### ISSUE TITLE
Support for consts in addition to literals

### ISSUE THREAD

**Issue by U007D** [lovasoa/custom_error#13]
In my production code, I often consolidate my string resources into a single module/set of files (localization).

```rust
use custom_error::custom_error;
use std::io::Error as IoError;

mod msg {
    pub const ERR_IO_ERROR: &str = "IoError encountered";
}

custom_error!{
    pub Error
        NoneError{ source: IoError } = msg::ERR_IO_ERROR,
}
```

Unfortunately, this does not work:
```bash
error: expected a literal
  --> src/error.rs:11:40
   |
11 |         NoneError{ source: IoError } = msg::ERR_IO_ERROR,
   |                                        ^^^^^^^^^^^^^^^^^
   |
   = note: only literals (like `"foo"`, `42` and `3.14`) can be passed to `concat!()`
```

But it could if the expansion looked something like this:
```rust
mod msg {
    pub const ERR_IO_ERROR: &str = "IoError encountered";
}

use std::{
    fmt::{
        Display,
        Formatter,
        Result as FmtResult,
    },
    io::Error as IoError,
};

#[derive(Debug)]
pub enum Error {
    IoError(IoError),
}

impl Display for Error {
    fn fmt(&self, f: &mut Formatter) -> FmtResult {
        write!(f, "{}", match self {
            Error::IoError(err) => format!("{} source: {:?}", msg::ERR_IO_ERROR, err),
        })
    }
}
```

**Comment by lovasoa** [comment]
Well, I am not sure whether this can be done with the current implementation... The expansion you suggest would not work for the case where the error message depends on the parameters, such as this example from the README: 

```rust
custom_error!{SantaError
    BadChild{name:String, foolishness:u8} = "{name} has been bad {foolishness} times this year",
    TooFar                                = "The location you indicated is too far from the north pole",
    InvalidReindeer{legs:u8}              = "The reindeer has {legs} legs"
}
```

**Comment by lovasoa** [comment]
However, you can achieve what you want using [advanced custom error messages](https://github.com/lovasoa/custom_error#advanced-custom-error-messages).

And in your case, I'm not sure handling localization directly in the `Display` implementation is a good idea anyway. I would suggest having your own `LocalizedDisplay` trait and implementing it for your error messages. That would avoid mixing localized and non-localized strings, since the standard library (as well as most third-party libraries) use english in their implementation of `Display`.

**Comment by U007D** [comment]
The key for me is not to have the strings intermixed with logic, which it appears I can achieve with the advanced custom error messages feature.  Thank you for the suggestions!
